### ISSUE TITLE
Addition of std::back_inserter use to Read component

### ISSUE THREAD

**Issue by Maktm** [RaptorFactor/hadesmem#4]
This is question as to whether it would be better to use std::back_inserter for all uses of std::copy inside of the read component (e.g. https://github.com/RaptorFactor/hadesmem/blob/master/include/memory/hadesmem/read.hpp#L69).
In the current state the user would need to ensure that the container supplied already contains the number of elements to read but with std::back_inserter there would be less worry for users of the API (and less prone to runtime errors due to empty/insufficient container sizes).

Possible implementation:

std::copy(std::begin(data), std::end(data), std::back_inserter(out));

**Comment by RaptorFactor** [comment]
I can't test until tomorrow, but doesn't Read take an OutputIterator? And back_inserter makes an output iterator from a container. So the following should be possible:

std::vector<int> v;
Read<int>(process, address, std::back_inserter(v));

Or is that incorrect and/or insufficient?

**Comment by RaptorFactor** [comment]
I can't check this properly yet (still at work), but I quickly tested the following snippet, which should be similar to how Read should work:

```
#include <algorithm>
#include <iterator>
#include <vector>

template <typename T, typename Iter>
void ContrivedExample(const T* beg, const T* end, Iter out)
{
  std::copy(beg, end, out);
}

int main() {
  const int a[] = { 1, 2, 3, 4, 5 };
  std::vector<int> v;
  ContrivedExample(std::begin(a), std::end(a), std::back_inserter(v));
  for (const auto& e : v) {
    std::printf("%d", e);
  }
}

```
P.S. I might be completely misunderstanding your scenario so please do argue with me if I'm wrong.

**Comment by Maktm** [comment]
Yeah my mistake. But shouldn't this code be able to compile?

`#include <iostream>
#include <string>
#include <vector>

#include <hadesmem/detail/trace.hpp>
#include <hadesmem/read.hpp>

int main(int argc, char* argv[])
{
  int n[] = {1, 2, 3, 4};
  hadesmem::Process const process{
    ::GetCurrentProcessId()};
  std::vector<int> v;
  hadesmem::Read<int>(
    process,
    std::addressof(n),
    std::back_inserter(v));
  return EXIT_SUCCESS;
}`

**Comment by RaptorFactor** [comment]
Can't test until tonight, but that looks wrong to me because Read has no way to know the size? What if you do something like this instead:

`hadesmem::Read<int>(process, std::addressof(n), _countof(n), std::back_inserter(v));`

There's also one which takes the size as a template param:
```
// Can't remember if _countof makes a constant expression or not but you get the idea
hadesmem::Read<int, _countof(n)>(process, std::addressof(n), std::back_inserter(v));
```

ReadString supports the interface you're using above, because it has a natural way to know when to stop (i.e. when it hits a null character). Perhaps this could be generalized to take a predicate and then the interface could be the same across all the different Read variants.

Then we could do:
`hadesmem::Read<int>(process, address, std::back_inserter(v), [](int i) { return i != 42});
`

Thoughts? Did I get any of that mixed up? (I'm just quickly checking the code in the browser, can't compile anything right now.)

**Comment by RaptorFactor** [comment]
This compiles for me:

```
  std::vector<int> int_list_read_bi;
  hadesmem::Read<int>(process, int_list.data(), int_list.size(), 
    std::back_inserter(int_list_read_bi));
  BOOST_TEST(int_list == int_list_read_bi);
```

I still think having a generic overload taking a predicate makes sense, but is the original issue addressed?

**Comment by Maktm** [comment]
Yeah it was just me being stupid. Thanks for clarifying everything.
